### ISSUE TITLE
How many @s?

### ISSUE THREAD

**Issue by edeutsch** [NCATS-Tangerine/NCATS-ReasonerStdAPI#1]
If we want to do JSON-LD, this format seems to like to use @ symbols in front of some keys, especially @context, @id, @type. But @cmungall says you don't need it. However Michel Dumontier appears to be lobbying for them.

Eric find that they seem to be a pain because at least for the python auto-generated classes via the OpenAPI/Swagger generation, dealing with @ symbols appears to be a pain.

For now, I've left them all out except for @context, which maybe is necessary?? Actually in the RTX version, we just use context because the auto-generated class doesn't have @context. Might need to write a custom serializer to do that properly?

**Comment by patrickkwang** [comment]
It seems like integration of OpenAPI and JSON-LD is not a high priority.
https://github.com/OAI/OpenAPI-Specification/issues/1100

**Comment by VladimirAlexiev** [comment]
@edeutsch What was the outcome then? Did you cancel JSONLD compatibility?

You need the `@` in `@context` if the context is specified in the response body. You could also provide the context as a link header. Then the context can define aliases without `@` for `type id value` etc, that is done often.

**Comment by edeutsch** [comment]
Unless there is lobbying for it, I think any use of @ before any keys is cancelled. It has not been in the last few versions, and everyone seemed okay with that.
