### ISSUE TITLE
please use identifiers.org as the source for biomedical curies /uris

### ISSUE THREAD

**Issue by edeutsch** [NCATS-Tangerine/NCATS-ReasonerStdAPI#24]
Michel Dumontier said:
please use identifiers.org as the source for biomedical curies /uris
and
let me refer you to: https://www.nature.com/articles/sdata201829

**Comment by edeutsch** [comment]
As far as I'm aware we still do not have consensus on what the official CURIE prefixes are. @cmungall  says "use BioLink", but there seem to be TWO different documents in BioLink with CURIES defined in them and they are not fully aligned. Michel says "use identifiers.org", also a worthy source. But they are not the same in many cases. Even ignoring the issue of CapiTaliZation, one says "pubmed" and the other says "PMID". which will we choose? The most relevant issues are described here:
https://docs.google.com/spreadsheets/d/1BCtJWyz9WpwI-myN3HwWkwsjxvUNr1OrdGU60QCs2Uw/edit

I strongly advocate that we gather the relevant stakeholders here and make a concrete decision and document it in the above Google doc. Perhaps Monday?

**Comment by edeutsch** [comment]
Michel does not appear to be part of this repo or org. How do we get him here?

**Comment by cmungall** [comment]
http://obofoundry.org/ontology/hancestro.html

**Comment by micheldumontier** [comment]
need access to the google spreadsheet

**Comment by edeutsch** [comment]
granted. If anyone else needs access, just request it.

**Comment by micheldumontier** [comment]
Identifiers.org is an infrastructure established by the EBI to specifically handle the registration and description of resource prefixes. Each resource can be described with a set of metadata including regular expressions for syntactic validation. They offer a wide array of services related to this (http://identifiers.org/about), have multiple sources of funding and can be expected to persist into the future well beyond the lifetime of the translator project. Alignment with identifiers.org, either implicitely where the prefix exactly matches the identifiers.org record and/or explicitely in that the biolink context file links directly to an identifiers.org entry is essential part of what it means to make things FAIR.

**Comment by patrickkwang** [comment]
This is out of scope for the API syntax; please refer to modeling resources:
https://nodenormalization-sri.renci.org/apidocs/
https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L2104

In particular, the Biolink model includes a prioritized list of id prefixes for each semantic type.
