### ISSUE TITLE
Version 0.9.0 has been added

### ISSUE THREAD

**Issue by edeutsch** [NCATS-Tangerine/NCATS-ReasonerStdAPI#25]
A draft of version 0.9.0 has been committed. Please examine and comment in this thread. Note that at present, the YAML is up to date and the pptx-based graphical depiction is up-to-date, but I haven't had a chance to sync the markdown file yet. Still to do..

**Comment by srensi** [comment]
Does "previous_message_processing_plan" == "message envelope"?  I am referring to Query object schema.

**Comment by edeutsch** [comment]
Yes. where previous_message_processing_plan{} is the JSON-visible attribute name, and MessageEnvelope is the JSON-invisible YAML class name that contains other components. I suppose there's no good reason that they're called something completely different except history. RTX already has an autogenerated class MessageEnvelope from the hackathon and no one else is using it yet, so I thought I'd just keep the class name the same. But, changing it to something more sensibly name seems reasonable.

**Comment by edeutsch** [comment]
Documentation has been substantially cleaned up. yaml, pptx, and md are all in sync now, I believe. Ready for implementation?

**Comment by patrickkwang** [comment]
I think this is resolved. Future discussions of this sort can be conducted over pull requests.
