### ISSUE TITLE
How to encode the knowledge map?

### ISSUE THREAD

**Issue by edeutsch** [NCATS-Tangerine/NCATS-ReasonerStdAPI#27]
The proposed knowledge_map scheme was defined like this:
  KMap:
    description: "Map from question node and edge IDs to knowledge-graph entity identifiers and relationship references"
    type: object
    additionalProperties:
type: string

And an example was provided like this:
[
 {
   "n00": "MONDO:0005737",
   "n01": "HGNC:17770",
   "e00": "316"
 },
 {
   "n00": "MONDO:0005737",
   "n01": "HGNC:13236",
   "e00": "320"
 }
]
(hopefully GitHib issue tracker doesn't make a mess of this JSON)

This strikes me as difficult to document validate. As a counter-proposal, I modeled it like this instead:
  NodeEdgeNodeTriple:
    type: "object"
    description: "A node-edge-node triple binding a result to both the QueryGraph and KnowledgeGraph"
    properties:
      nodeA_QG_node_id:
        type: "string"
        example: "n00"
        description: "QueryGraph internal identifier for a QNode"
      nodeA_KG_id:
        type: "string"
        example: "OMIM:603903"
        description: "CURIE identifier for this node in the KnowledgeGraph"
      nodeB_QG_node_id:
        type: "string"
        example: "n01"
        description: "QueryGraph internal identifier for a QNode"
      nodeB_KG_id:
        type: "string"
        example: "UNIPROT:P01234"
        description: "CURIE identifier for this node in the KnowledgeGraph"
      edge_QG_edge_id:
        type: "string"
        example: "e00"
        description: "QueryGraph internal identifier for a QEdge"
      edge_KG_id:
        type: "string"
        example: "553903"
        description: "Local identifier for this node which is unique within this KnowledgeGraph, and perhaps within the source reasoner's knowledge graph"
    additionalProperties: true

This is more explicit and easily documented and validated. But it is a lot more verbose.

What do you think? Go for compact or go for explicit?

**Comment by patrickkwang** [comment]
My understanding from reading through the yaml is that each Result would have a list of these NodeEdgeNodeTriples, but it's not clear to me how these can be used to describe a general answer. We should be able to use the information provided by this question/KG/binding framework to reproduce e.g. the Result's result_graph.

The compact example above describes two independent answers. These answers happen to contain exactly two nodes and one edge, but will in general have an arbitrary number of nodes and edges corresponding to the elements in the question graph.

**Comment by edeutsch** [comment]
So, slightly off-topic question about the knowledge map scheme:
Say my question is "Which drugs inhibit COX1?"
Answer #1: (aspirin) -- inhibits --> (PTGS1)
Answer #2: (loxoprofen) -- is_a --> (NSAID) -- inhibits --> (PTGS1)
How do we do that in the knowledge_map scheme?

**Comment by patrickkwang** [comment]
It will be the reasoner module's job to produce their answers in the format requested by the message. If the question asks for `(n0)-[inhibits]->(PTGS1)`, then the reasoner will need to internally infer that `(loxoprofen)-[is_a]->(NSAID)-[inhibits]->(PTGS1)` implies `(loxoprofen)-[inhibits]->(PTGS1)`.

**Comment by edeutsch** [comment]
okay, fair enough. I will just revert the schema to what Patrick originally had then:
KMap:
description: "Map from question node and edge IDs to knowledge-graph entity identifiers and relationship references"
type: object
additionalProperties:
type: string

A simple lookup table Dict. Unless anyone else has comments on this aspect?

**Comment by edeutsch** [comment]
YAML and pptx updated with latest consensus. Further comments?

**Comment by edeutsch** [comment]
Since no further comments, closing this issue.
