### ISSUE TITLE
Query Endpoint Not Working Out of The Box (v0.9.0)

### ISSUE THREAD

**Issue by srensi** [NCATS-Tangerine/NCATS-ReasonerStdAPI#28]
Trying out Query endpoint with given example input returns status code 400.
 
**Request Body:**
{
  "asynchronous": "False",
  "bypass_cache": "true",
  "max_results": 100,
  "page_number": 1,
  "page_size": 100,
  "previous_message_processing_plan": "{}",
  "query_message": "{}",
  "reasoner_ids": [
    "reasoner",
    "Robokop",
    "Indigo"
  ]
}

**Response:**
{
  "detail": "'{}' is not of type 'object'",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}

Deleting "message" and "previous_message_processing_plan" fields from the request resolves the error.

**Comment by edeutsch** [comment]
No, I have not deployed it yet. We're still arguing over the schema. Once we're all sufficiently happy with the schema, then I'll deploy it and then there will be lots of code to change to support it (for RTX at least).

**Comment by srensi** [comment]
Thanks for the clarification!
