### ISSUE TITLE
Required fields

### ISSUE THREAD

**Issue by patrickkwang** [NCATS-Tangerine/NCATS-ReasonerStdAPI#29]
Version 0.9.0 includes multiple ways to transmit information:
* in `Message`, `query_type_id` and `terms` vs. `query_graph`
* in `Result`, `result_graph` vs. `knowledge_map`

There are also a lot of other fields that may or may not be desired or provided by different reasoners.

In order to build a reasoner module that implements this format, or an algorithm to call such modules, we need to know which elements are required. Reasoner modules must implement at least the required elements, and the meta-algorithm should be okay in cases where anything not-required is missing.

In cases where we'd like to require `A` OR `B`, OpenAPI 3.0 provides the `oneOf` keyword (I'm not sure if this is available in 2.0). Using this structure, `Message` could, for example, require `query_type_id` AND `terms` OR `query_graph`. This may not be ideal for interoperability purposes, but it would give us a place to start.

**Comment by edeutsch** [comment]
I was thinking that this might be best left to some additional documentation and policies and letting the code make decisions based on what is available, rather than prescribing requirements in the YAML. One could even see some benefits to letting a reasoner output both styles as we learn how to support the new format. But I don't feel strongly. If you'd like to propose which fields you think should be required, we could have those discussions.

**Comment by patrickkwang** [comment]
We've now split the specification into two versions: a 'minimal' version that every reasoner ought to support, and an 'optional' version providing standards for additional properties/functionality (e.g. message/feedback storage mechanisms).
This is getting at a problem that we've always had and never really addressed. Namely, an OpenAPI document describes a specific API rather than a class of APIs. When the OpenAPI documentation indicates that an input parameter is optional, that means it's optional for the client of that API, but the server will always handle the parameter if it is provided. To specify that different servers may support different sets of optional parameters, we need these two versions of the OpenAPI document.
All of this is to illustrate that indicating that certain fields in e.g. [Query](https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI/blob/master/API/TranslatorReasonersAPI.yaml#L48) are required is not sufficient, because even 'optional' properties like `asynchronous` must be supported by the server. The solution is to remove these fields entirely from the minimal OpenAPI document, indicating that not all reasoners must support them. They will remain in the optional OpenAPI document to provide standardization between reasoners that do intend to support them.
Each reasoner's individual OpenAPI document will indicate which parameters and fields it supports.
