### ISSUE TITLE
Expose biothings explorer as ReasonerStdAPI 0.9.x

### ISSUE THREAD

**Issue by cmungall** [NCATS-Tangerine/NCATS-ReasonerStdAPI#42]

**Comment by patrickkwang** [comment]
Probably this issue should go [here](https://github.com/biothings/biothings_explorer).

**Comment by andrewsu** [comment]
FYI this was implemented in https://github.com/biothings/biothings_explorer/issues/37, and compliance is tested via the Reasoner Std API validator in the BTE CI tests.
