### ISSUE TITLE
Ensure all reasoners conforming are registered

### ISSUE THREAD

**Issue by cmungall** [NCATS-Tangerine/NCATS-ReasonerStdAPI#43]
Add a file here for each reasoner:

https://github.com/NCATS-Tangerine/translator-api-registry/

**Comment by patrickkwang** [comment]
ROBOKOP: https://github.com/NCATS-Tangerine/translator-api-registry/pull/19

**Comment by patrickkwang** [comment]
This is not an issue with the documents in this repository. 😁
