### ISSUE TITLE
Reasoner API needs additional fields to conform to SmartAPI

### ISSUE THREAD

**Issue by cmungall** [NCATS-Tangerine/NCATS-ReasonerStdAPI#44]
I tried to register

https://raw.githubusercontent.com/NCATS-Tangerine/NCATS-ReasonerStdAPI/master/API/TranslatorReasonersAPI.yaml

here:

https://smart-api.info/add_api

in dry-run mode

I get

```
ValidationError
[SmartAPI] 'info': 'termsOfService' is a required property
```

**Comment by newgene** [comment]
@cmungall @patrickkwang `termsOfService` is required in SmartAPI specs (optional for the plain OpenAPI).

**Comment by patrickkwang** [comment]
Yeah, thanks for the reminder. This wasn't a quick fix only because we don't actually have a terms of service document. I can put in some placeholder if it's just a technical compatibility issue. Alternatively, does anyone have experience generating some kind of reasonable terms of service?

**Comment by newgene** [comment]
We have this: http://mygene.info/terms and I saw Monarch has this: http://monarchinitiative.org/page/disclaimer. Feel free to modify it to fit your need.

@cmungall should reasoner APIs have a common terms template hosted somewhere, so all reasoner APIs can put the same link for this `termsofService` field?

**Comment by cmungall** [comment]
I don't have any strong opinions

>

**Comment by patrickkwang** [comment]
Thanks, @newgene. After further consideration, I think a placeholder is actually what's called-for here. The documents in this repo are intended as standards and guidelines on which reasoner APIs should be based. I don't see any need to standardize the terms of use, and putting some recommendation in here smacks of legal advice, which is not our business. Putting some kind of placeholder in here would indicate to API implementers that they ought to specify some terms of use, but they can work out the details independently.

**Comment by patrickkwang** [comment]
5b0e2dba858eb7a4051fdaf5e5d0b6337a3c43df
TranslatorReasonersAPI.yaml now passes the SmartAPI validation.
