### ISSUE TITLE
KnowledgeGraph <-> RemoteKnowledgeGraph ambiguity

### ISSUE THREAD

**Issue by patrickkwang** [NCATS-Tangerine/NCATS-ReasonerStdAPI#48]
Since the two alternatives do not specify any conflicting fields and `RemoteKnowledgeGraph` allows `additionalProperties: true`, it is not possible, formally, to determine which alternative a given `Message` instance is attempting to use as long as its `knowledge_graph` contains the `nodes` and `edges` fields required by `KnowledgeGraph`. It we make some fields of `RemoteKnowledgeGraph` required, that will make things easier, but it would be nice if we could eliminate the possibility of additional properties, which would ensure that we could always disambiguate these.

**Comment by edeutsch** [comment]
fine to remove additionalProperties: true on RemoteKnowledgeGraph if that what you're hinting at. We have no plans to support that any time soon, fine to make any changes you like to that.

**Comment by patrickkwang** [comment]
Call me an idealist, but I think the question here ought to be not how changes to the spec would disturb any specific implementation of the reasoner service, but instead what the _right thing to do_ is. To my knowledge, no one uses `RemoteKnowledgeGraph` right now. But if one were to use it, would we need the ability to specify any properties other than a url and credentials?

The idea here is that the node/edge ids provided in the bindings are assumed to match the internal ids, or some "id" property, of the nodes/edges in the remote knowledge graph. One hole I see here is that this was developed assuming a remote Neo4j instance that can be queried with Cypher, but KG exist in many other formats with different query protocols. So we probably need some way to specify either a) what kind of KG we're pointing to, or b) the specifics of how to talk with it. (a) seems simpler.

**Comment by edeutsch** [comment]
I would agree that 'protocol' would be a fine attribute to add, that seems sensible. The 'protocol' might be 'cypher' or perhaps something else eventually. It occurs to me that it would be pretty easy to implement API endpoints that provide the information as well. In fact, we already have it for nodes. We would have to add something for edges.

**Comment by patrickkwang** [comment]
In attempting to do this, the validator behavior was confusing me for a while because `additionalProperties: true` is actually the default behavior:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#properties
To turn this off you must specify `additionalProperties: false`.

**Comment by patrickkwang** [comment]
#78
