### ISSUE TITLE
ERRORUNKNOWN Class

### ISSUE THREAD

**Issue by srensi** [NCATS-Tangerine/NCATS-ReasonerStdAPI#52]
This is for reasoner standard 0.9.0 and OpenAPI 2.0.  When I generate a flask sever using the OpenAPI codegen, every model class except "base", "massage_terms", "node_attributes", and "result" has the following line inserted with the rest of the imports.

from swagger_server.models.errorunknown import ERRORUNKNOWN  # noqa: F401,E501

If I delete this line from each of the model class definition files then everything seems to run ok.

**Comment by edeutsch** [comment]
The latest file is now tagged 0.9.1.
Note that OpenAPI 2.0 is a bit of a misnomer, it is either Swagger 2.0 or OpenAPI 3.0.1 at this point. 
The Swagger 2.0 codegen is here:
`docker pull swaggerapi/swagger-codegen-cli`
But that probably doesn't work with the latest yaml without some changes.
The OpenAPI 3.0.1 codegen is here:
`docker pull openapitools/openapi-generator-cli`
This seems to work for me.
In any case, I have never seen the models.errorunknown problem with either codegen, so I don't know what to suggest here.
