### ISSUE TITLE
Currently the Reasoner API standard does not specify curies, id prefixes, namespaces -- we may want to consider a single unified service for Translator id resolution

### ISSUE THREAD

**Issue by realmarcin** [NCATS-Tangerine/NCATS-ReasonerStdAPI#59]
... to avoid variations on the translation which could impact results and make comparisons more challenging

**Comment by patrickkwang** [comment]
Gamma publishes two helpful services:
http://robokop.renci.org:6010/apidocs/#/util/post_api_synonymize__node_id___node_type__
http://robokop.renci.org:6010/apidocs/#/util/post_api_normalize
But there are not really any guidelines or standards for using them.

**Comment by patrickkwang** [comment]
These services are now provided and supported by the SRI team:
https://nodenormalization-sri.renci.org/apidocs/
https://edgenormalization-sri.renci.org/apidocs/
http://robokop.renci.org:2434/docs
