### ISSUE TITLE
oneOf in Node and Edge Bindings breaks codegen

### ISSUE THREAD

**Issue by srensi** [NCATS-Tangerine/NCATS-ReasonerStdAPI#72]
The oneOf type property for node_binding and edge_binding objects is breaking the codegen for the python-flask (and node) server.  Changing to either a string or array type fixes the problem.

Bug is @ Lines 124 and 139 of TranslatorReasonersAPI.yaml.  Went over with Patrick, and apparently this is a known issue with OpenAPI 3.0.  

https://github.com/OpenAPITools/openapi-generator/search?q=oneof&type=Issues

**Comment by patrickkwang** [comment]
To be clear, this is a bug with [openapi-generator](https://github.com/OpenAPITools/openapi-generator). [TranslatorReasonersAPI.yaml](https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI/blob/master/API/TranslatorReasonersAPI.yaml) is fully compliant with the OpenAPI 3.0 specification, as far as I know.

**Comment by patrickkwang** [comment]
Maybe https://github.com/OpenAPITools/openapi-generator/issues/1663.
