### ISSUE TITLE
OpenAPI 3.0 Generator (Python) - The swagger_ui directory could not be found

### ISSUE THREAD

**Issue by srensi** [NCATS-Tangerine/NCATS-ReasonerStdAPI#73]
Launching server raised the following warning/message: "The swagger_ui directory could not be found".  UI page was 404

Fixed by adding "swagger-ui-bundle" to requirements.txt file.  Solution described in this post: https://github.com/zalando/connexion/issues/779

**Comment by patrickkwang** [comment]
Sounds like an issue with a particular python server. Maybe this was posted to the wrong repo?
