### ISSUE TITLE
[Connexion] fxn() missing 1 required positional argument: 'body'

### ISSUE THREAD

**Issue by srensi** [NCATS-Tangerine/NCATS-ReasonerStdAPI#74]
This also looks to be an error with the code generator for python-flask.  It is really two issues rolled into one...

**First Issue**
All of the controller stubs are initialized with a "body" parameter: `fxn(body)`

The problem is that the Query object schema is defined with: `x-body-name: request_body`

The fix is to change all the controller function signatures to `fxn(request_body)`.  Deleting the positional argument also works.

***Second Issue***
The default controller code stub tries to initialize the JSON payload as a Dict object, which is not being imported by default.   The fix is to either add `from typing import List, Dict` to your imports, or just import the model of your choice and initialize to that.

**Comment by patrickkwang** [comment]
You're using openapi-generator here, yes?
That `x-body-name: request_body` was added to _fix_ an issue with code generation: #46
Has something gone wrong since then because a) we broke it somehow, or b) openapi-generator has changed, or c) something else?
Perhaps @lhannest can provide some insight.

**Comment by srensi** [comment]
Update...

This looks like an issue with the code generator.  When I generated using the online swagger editor (https://editor.swagger.io/), I got the `body` parameters in my controller stub signitures.  When I generated with the docker-cli tool (openAPI 3.0), it filled in the parameters as `request_body`.  It also initialized the objects correctly.

**Comment by patrickkwang** [comment]
👍
