### ISSUE TITLE
additionalProperties?

### ISSUE THREAD

**Issue by srensi** [NCATS-Tangerine/NCATS-ReasonerStdAPI#79]
I'm getting some weird behavior where additional properties are getting dropped when I initialize node and edge objects.  

Internal edge representation:
```
{'id': '4e926e',
   'source_id': 'MESH:D012893',
   'target_id': 'MESH:D011475',
   'weight': 0.0034542314335060447}
```
JSON output:
```
{'id': '4e926e', 
    'source_id': 'MESH:D012893', 
    'target_id': 'MESH:D011475'},
```

I am using the openAPI 3.0 generator-cli (docker:latest) to generate a python-flask server.  The swagger 2.0 code generator doesn't seem to have this problem with additionalProperties, but the model stubs it generates don't seem to have any of the specified properties in them....

**Comment by patrickkwang** [comment]
https://github.com/OpenAPITools/openapi-generator/issues/2028
https://github.com/OpenAPITools/openapi-generator/issues/2078
https://github.com/OpenAPITools/openapi-generator/pull/2049
