### ISSUE TITLE
Simplify alignment of minimal and optional specs

### ISSUE THREAD

**Issue by patrickkwang** [NCATS-Tangerine/NCATS-ReasonerStdAPI#82]
One option is for the optional spec to extend the minimal spec by referencing it with `allOf`:
https://json-schema.org/understanding-json-schema/structuring.html#extending

I'm not confident in tools like swagger-ui and openapi-generator to handle multi-file schemas, so it will probably be necessary to merge them before applying these.

**Comment by edeutsch** [comment]
Sounds interesting, but I think it would be much clearer to have a minimal spec and an maximal (optional) spec that users can examine separately and choose from. I suppose I didn't understand it before, but perhaps optional was not meant to be a complete superset of the primary. Some items were repeated and some were not and some where extended. I found it very difficult to understand the details of the differences between the two. I think by repeating everything in primary into _optional, it becomes easy to appreciate the differences with a simple diff. Previously, the diff was messy and confusing.

**Comment by patrickkwang** [comment]
To ensure interoperability, the optional spec _must_ be a superset of the minimal spec. They drifted apart mostly due to laziness on my part. Explicitly referencing would make it easier to keep them in sync, and would hopefully make it clear which fields the optional spec adds. It's not as easy to pull off as I was imagining, though, because we have differences at multiple levels of the hierarchy (e.g. extra fields in message and in message.knowledge_graph.nodes[]). Perhaps we instead just need some kind of test to ensure that the two remain aligned.

**Comment by patrickkwang** [comment]
86033922211b0672b1a905b0b58b3f3c3b65d683
