### ISSUE TITLE
str vs. list(str)

### ISSUE THREAD

**Issue by patrickkwang** [NCATS-Tangerine/NCATS-ReasonerStdAPI#86]
There are a number of places where this should be addressed:

- query_graph.nodes[].curie
- query_graph.nodes[].type
- query_graph.edges[].type
- results[].node_bindings[].kg_id
- knowledge_graph.nodes[].type

Probably more. My first instinct is to allow any of these to be either a string or list of strings, with some shared understanding of what it means to have a list for e.g. a query-graph node type.

**Comment by edeutsch** [comment]
I agree, this seems reasonable, something we should already have done.
