### ISSUE TITLE
Use objects instead of lists for *graph nodes and edges

### ISSUE THREAD

**Issue by patrickkwang** [NCATS-Tangerine/NCATS-ReasonerStdAPI#94]
Anecdotally, when parsing a query_graph or knowledge_graph in Python, I almost always want a map from node/edge ids to the corresponding details, and I have to construct this whenever I receive a new *graph. If the native format were that map instead of the current list, it would be handy.

This change would also make enforceable the currently unstated requirement that node/edge ids must be unique.

**Comment by edeutsch** [comment]
yeah, I agree, this was my fault from long ago. I think there are a couple other places where we should reconsider lists like node_attributes[] and edge_attributes[]. Anyway, I assume there'll be no action on this before the March demos, but I would highly encourage that we reconsider this in April. This will be a huge breaking change everywhere if we do change it. But it probably makes sense to do.

**Comment by patrickkwang** [comment]
#101
